FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./


# Bundle app source
COPY . .

EXPOSE 8080
run npm install
CMD [ "npm", "start" ]